# 使用官方 Node.js 镜像进行构建
FROM node:22 AS build
RUN npm install -g pnpm
# 设置工作目录
WORKDIR /app

# 复制前端代码到容器
COPY /hrs_client/package.json /app
COPY /hrs_client/pnpm-lock.yaml /app

RUN pnpm install

# 复制源代码并进行构建
COPY /hrs_client /app
RUN pnpm run build
RUN ls -la /app

# 使用 Nginx 镜像来托管前端应用
FROM nginx:alpine
RUN apk add --no-cache vim

# 复制构建好的前端文件到 Nginx 默认目录
COPY --from=build /app/dist /usr/share/nginx/html

# 暴露端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]
