# 使用 Node.js 镜像作为基础镜像
FROM node:22

# 设置工作目录
WORKDIR /app

# 复制后端代码到容器
COPY /hrs_server/package.json /app
COPY /hrs_server/pnpm-lock.yaml /app
RUN npm install -g pnpm
RUN pnpm set registry https://registry.npmmirror.com/
RUN pnpm install

# 复制后端代码
COPY /hrs_server /app
# 编译 TypeScript 代码
RUN pnpm run build
# 暴露后端 API 服务端口
EXPOSE 3000

# 启动后端应用
CMD ["pnpm", "start:prod"]
